In [33]:
import tensorflow as tf

In [3]:
conda install -y-c anaconda pandas

^C

Note: you may need to restart the kernel to use updated packages.


In [34]:
np.__version__

'1.23.2'

In [35]:
import numpy as np

In [5]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [6]:
#스칼라 정의(상수)
a = tf.constant(1.)
b = tf.constant(2.)
print(a)
print(b)

tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(2.0, shape=(), dtype=float32)


In [7]:
print(tf.rank(a))

tf.Tensor(0, shape=(), dtype=int32)


In [8]:
c = 1.0

In [9]:
print(type(a),type(c))

<class 'tensorflow.python.framework.ops.EagerTensor'> <class 'float'>


In [10]:
#자료형 변환
a = tf.cast(a, tf.int32)
b = tf.cast(b, tf.int32)
print(a.dtype)
print(b.dtype)

<dtype: 'int32'>
<dtype: 'int32'>


In [11]:
print(tf.math.subtract(a,b))

tf.Tensor(-1, shape=(), dtype=int32)


In [14]:
print(tf.math.divide(a,b))

tf.Tensor(0.5, shape=(), dtype=float64)


In [15]:
print(tf.math.mod(a,b))

tf.Tensor(1, shape=(), dtype=int32)


In [16]:
print(tf.math.floordiv(a,b))

tf.Tensor(0, shape=(), dtype=int32)


In [31]:
#벡터 정의
py_list = [10.,20.,30.]#파이썬 리스트
num_arr = np.array([10.,10.,10.])# 넘파이 배열
vec1 = tf.constant(py_list, dtype=tf.float32)#float뒤 숫자는 바이트를 나타냄
vec2 = tf.constant(num_arr, dtype=tf.float32)
print(vec1)
print(vec2)

tf.Tensor([10. 20. 30.], shape=(3,), dtype=float32)
tf.Tensor([10. 10. 10.], shape=(3,), dtype=float32)


In [32]:
print(tf.rank(vec1))
print(tf.rank(vec2))

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [33]:
add1 = tf.math.add(vec1,vec2)
print(add1)
print(tf.rank(add1))

tf.Tensor([20. 30. 40.], shape=(3,), dtype=float32)
tf.Tensor(1, shape=(), dtype=int32)


In [34]:
print(vec1 - vec2)

tf.Tensor([ 0. 10. 20.], shape=(3,), dtype=float32)


In [35]:
print(tf.reduce_sum(vec1))

tf.Tensor(60.0, shape=(), dtype=float32)


In [36]:
print(tf.math.square(vec1))

tf.Tensor([100. 400. 900.], shape=(3,), dtype=float32)


In [37]:
#제곱근
print(tf.math.sqrt(vec2))

tf.Tensor([3.1622777 3.1622777 3.1622777], shape=(3,), dtype=float32)


In [38]:
#브로드 캐스팅(스칼라+벡터)
#매트릭스
list_of_list = [[10,20],[30,40]]
mat1 = tf.constant(list_of_list)
print('rank',tf.rank(mat1))
mat1

rank tf.Tensor(2, shape=(), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]])>

In [39]:
mat2 = tf.stack([vec1,vec2])
print(tf.rank(mat2))
mat2

tf.Tensor(2, shape=(), dtype=int32)


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[10., 20., 30.],
       [10., 10., 10.]], dtype=float32)>

In [40]:
mat2 = tf.constant(list_of_list)

In [43]:
# element by element 연산
element_mul = tf.math.multiply(mat1,mat2)
print('result',element_mul)
print('rank',tf.rank(element_mul))

result tf.Tensor(
[[ 100  400]
 [ 900 1600]], shape=(2, 2), dtype=int32)
rank tf.Tensor(2, shape=(), dtype=int32)


In [44]:
element_bc = tf.math.multiply(mat1, 3)
print('result',element_bc)
print('rank',tf.rank(element_bc))

result tf.Tensor(
[[ 30  60]
 [ 90 120]], shape=(2, 2), dtype=int32)
rank tf.Tensor(2, shape=(), dtype=int32)


In [45]:
# 행렬곱(내적)
mat_mul = tf.matmul(mat1,mat2)
print('result',mat_mul)
print('rank',tf.rank(mat_mul))

result tf.Tensor(
[[ 700 1000]
 [1500 2200]], shape=(2, 2), dtype=int32)
rank tf.Tensor(2, shape=(), dtype=int32)


In [46]:
# 텐서플로우 넘파이로 바꾸기
np_arr = mat_mul.numpy()
print(type(np_arr))
np_arr

<class 'numpy.ndarray'>


array([[ 700, 1000],
       [1500, 2200]])

In [48]:
# 텐서 정의
mat1 = [[1,2,3,4],
        [5,6,7,8]]
mat2 = [[9,10,11,12],
        [13,14,15,16]]
mat3 = [[17,18,19,20],
        [21,22,23,24]]
tensor1 = tf.constant([mat1,mat2,mat3])
print('rank', tf.rank(tensor1))
print(tensor1)

rank tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)


In [51]:
vec = tf.constant([10,20,30,40,50])
print(vec)

tf.Tensor([10 20 30 40 50], shape=(5,), dtype=int32)


In [52]:
print(vec[0])

tf.Tensor(10, shape=(), dtype=int32)


In [53]:
print(vec[-1])

tf.Tensor(50, shape=(), dtype=int32)


In [54]:
print(vec[:])

tf.Tensor([10 20 30 40 50], shape=(5,), dtype=int32)


In [67]:
print(tensor1[2,1,1])

tf.Tensor(22, shape=(), dtype=int32)


In [60]:
mat = tf.constant([[10,20,30],
                   [40,50,60]])
print(mat[0,2])

tf.Tensor(30, shape=(), dtype=int32)


In [61]:
print(mat[0,:2])

tf.Tensor([10 20], shape=(2,), dtype=int32)


In [62]:
print(mat[1,:2])

tf.Tensor([40 50], shape=(2,), dtype=int32)


In [72]:
range(0,24)

range(0, 24)

In [73]:
# reshape
tensor = tf.constant(range(0,24))
print(tensor)


tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23], shape=(24,), dtype=int32)


In [81]:
tensor1 = tf.reshape(tensor,[4,2,3])
tensor1

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])>

In [84]:
tensor2 = tf.reshape(tensor1,[-1,4])
tensor2

<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])>

In [86]:
tensor3 = tf.reshape(tensor2,[-1])
tensor3

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])>

In [88]:
tensor4 = tf.reshape(tensor3, [3,2,4])
tensor4

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])>

In [92]:
tensor5 = tf.reshape(tensor4,[3,2,2,2])
tensor5

<tf.Tensor: shape=(3, 2, 2, 2), dtype=int32, numpy=
array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])>

In [93]:
tensor1 = tf.constant([[0,1,2,],
                       [3,4,5]])
print(tensor1)

tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int32)


In [95]:
tensor_var1 = tf.Variable(tensor1)#베리어블(변경이 가능한 변수) # tf.constant (상수 변경 x)
print(tensor_var1)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5]])>


In [96]:
print('이름', tensor_var1.name)
print('크기', tensor_var1.shape)
print('자료형', tensor_var1.dtype)
print('배열', tensor_var1.numpy())

이름 Variable:0
크기 (2, 3)
자료형 <dtype: 'int32'>
배열 [[0 1 2]
 [3 4 5]]


In [99]:
tensor_var1.assign([[1,1,1],[2,2,2]])
tensor_var1

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 2]])>

In [100]:
tensor2 = tf.convert_to_tensor(tensor_var1)
tensor2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 2]])>

In [101]:
tensor_var2 = tf.Variable(tensor2, name='new Name')
tensor_var2

<tf.Variable 'new Name:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 2]])>

In [103]:
tensor_var1 + tensor_var2 # 베리어블끼리 연산이 가능하다

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 2, 2],
       [4, 4, 4]])>

In [36]:
from tensorflow import keras

In [37]:
mnist = keras.datasets.mnist ## 연습용 데이터 가져오기
(X_train, y_train),(X_test,y_test) = mnist.load_data()

In [14]:
print(type(X_train))

<class 'numpy.ndarray'>


In [38]:
X_train.shape, y_train.shape

((60000, 28, 28), (60000,))

In [39]:
y_train[50000]

3

In [40]:
y_test.shape

(10000,)

In [18]:
np.min(X_train), np.max(X_train)

(0, 255)

In [19]:
X_train, X_test = X_train / 255.,X_test / 255. #minmax scaler

In [20]:
X_train[0]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

In [21]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),#벡터로 만들기(784)
    tf.keras.layers.Dense(256, activation='relu'),#뉴런을 맘대로 지정할수있음 /(relu)0보다 작으면 0으로 맞춰주고 0보다높으면 그대로 출력해준다(삼원색 표현은 0~255 음수는 필요없기때문에 바꿀필요가있음)
    tf.keras.layers.Dropout(0.2),# 20%의 데이터를 버림 오차가 없으면 오버피팅될 확률up
    tf.keras.layers.Dense(10, activation='softmax')#구분되는 갯수만큼만 만들기
])
#딥러닝의 알고리즘은 하나이다 (퍼셉트론)
# Sequential을 어떻게 구현하냐에 따라 달라짐 (논문참조)
# 뉴런 : 

In [22]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])#경사하강법 종류가많음 /원한인코딩이되어있으면 스팟스타그리

In [23]:
model.fit(X_train,y_train,epochs=10)

Epoch 1/10
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2554 - accuracy: 0.9253
Epoch 2/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1140 - accuracy: 0.9651
Epoch 3/10
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0826 - accuracy: 0.9739
Epoch 4/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0627 - accuracy: 0.9806
Epoch 5/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0533 - accuracy: 0.9830
Epoch 6/10
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0476 - accuracy: 0.9847
Epoch 7/10
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0383 - accuracy: 0.9875
Epoch 8/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0343 - accuracy: 0.9883
Epoch 9/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0313 - accuracy: 0.9895
Epoch 10/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.027

In [24]:
model.evaluate(X_test,y_test)

313/313 [==============================] - 1s 1ms/step - loss: 0.0686 - accuracy: 0.9809


[0.06855263561010361, 0.98089998960495]

In [140]:
!conda list pillow

# packages in environment at C:\Users\LSH\anaconda3\envs\test:
#
# Name                    Version                   Build  Channel


In [141]:
!conda install -y -c anaconda pillow

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\LSH\anaconda3\envs\test

  added / updated specs:
    - pillow


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    freetype-2.10.4            |       hd328e21_0         490 KB  anaconda
    libtiff-4.2.0              |       he0120a3_1         1.1 MB  anaconda
    libwebp-1.2.2              |       h2bbff1b_0         1.5 MB  anaconda
    lz4-c-1.9.3                |       h2bbff1b_1         141 KB  anaconda
    pillow-9.0.1               |   py38hdc2b20a_0        1023 KB  anaconda
    tk-8.6.12                  |       h2bbff1b_0         3.5 MB  anaconda
    zstd-1.5.2                 |       h19a0ad4_0         1.3 MB  anaconda
    ------------------------------------------------------------
                                           Total:         9.0 MB

The following NEW packages will be INSTAL

In [25]:
import os
from PIL import Image

In [26]:
os.getcwd()

'C:\\Users\\LSH\\Desktop\\AIschool\\machine learning\\python\\실습코드'

In [27]:
# image file 경로
cur_dir = os.getcwd()

In [28]:
image_path = os.path.join(cur_dir,'5.png')

In [29]:
image_path

'C:\\Users\\LSH\\Desktop\\AIschool\\machine learning\\python\\실습코드\\5.png'

In [30]:
cur_img = Image.open(image_path)

In [31]:
cur_img = cur_img.resize((28,28))#이미지 사이즈 조절

In [32]:
type(image)

NameError: name 'image' is not defined

In [33]:
image = np.asarray(cur_img)

In [34]:
image = np.mean(image, axis=2)# axis=2 이므로 z좌표로 진행된다

In [35]:
image = np.abs(255-image)#매트릭스에 스칼라데이터 합치면 브로드캐스팅
# X_train값과 같도록 맞춰줘야함

In [36]:
X_train[0]
image = image.astype(np.float32)/255.


In [37]:
image

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

In [177]:
!conda install -y -c conda-forge matplotlib

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\LSH\anaconda3\envs\test

  added / updated specs:
    - matplotlib


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    brotli-1.0.9               |       h8ffe710_7          18 KB  conda-forge
    brotli-bin-1.0.9           |       h8ffe710_7          21 KB  conda-forge
    cycler-0.11.0              |     pyhd8ed1ab_0          10 KB  conda-forge
    fonttools-4.37.1           |   py38h294d835_0         1.7 MB  conda-forge
    kiwisolver-1.4.4           |   py38hbd9d945_0          61 KB  conda-forge
    libbrotlicommon-1.0.9      |       h8ffe710_7          67 KB  conda-forge
    libbrotlidec-1.0.9         |       h8ffe710_7          33 KB  conda-forge
    libbrotlienc-1.0.9         |       h8ffe710_7         716 KB  conda-forge
    matplotlib-3.5.3           |   py38haa244fe_1           7 KB  con



==> WARNING: A newer version of conda exists. <==
  current version: 4.13.0
  latest version: 4.14.0

Please update conda by running

    $ conda update -n base conda




qt-5.9.7             | 91.1 MB   | ####4      |  45% 
qt-5.9.7             | 91.1 MB   | ####5      |  46% 
qt-5.9.7             | 91.1 MB   | ####6      |  46% 
qt-5.9.7             | 91.1 MB   | ####6      |  47% 
qt-5.9.7             | 91.1 MB   | ####7      |  47% 
qt-5.9.7             | 91.1 MB   | ####8      |  48% 
qt-5.9.7             | 91.1 MB   | ####8      |  49% 
qt-5.9.7             | 91.1 MB   | ####9      |  49% 
qt-5.9.7             | 91.1 MB   | ####9      |  50% 
qt-5.9.7             | 91.1 MB   | #####      |  51% 
qt-5.9.7             | 91.1 MB   | #####1     |  51% 
qt-5.9.7             | 91.1 MB   | #####1     |  52% 
qt-5.9.7             | 91.1 MB   | #####2     |  52% 
qt-5.9.7             | 91.1 MB   | #####2     |  53% 
qt-5.9.7             | 91.1 MB   | #####3     |  53% 
qt-5.9.7             | 91.1 MB   | #####4     |  54% 
qt-5.9.7             | 91.1 MB   | #####4     |  55% 
qt-5.9.7             | 91.1 MB   | #####5     |  55% 
qt-5.9.7             | 91.1 

In [38]:
import matplotlib.pyplot as plt

In [1]:
plt.imshow(X_train[0], cmap='gray')
plt.show()

NameError: name 'plt' is not defined

In [39]:
image = np.reshape(image, (1,28,28))
print(model.predict(image))
print('Model이 예측한 값은 {}입니다.'.format(np.argmax(model.predict(image),-1)))

[[4.8470210e-06 4.5423212e-06 5.6384753e-05 6.9226967e-03 3.3360809e-06
  9.5194900e-01 1.1284552e-04 5.7724252e-04 2.7372930e-04 4.0095426e-02]]
Model이 예측한 값은 [5]입니다.


In [47]:
y_train[4838]

4

In [50]:
cur_img

In [49]:
cur_img

In [65]:
num_list = []
num_list.append(input().split())
added = []


max(num_list)-min(num_list)

 1 2 3 4 5


TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [19]:
# 퍼셉트론(스칼라)
epsilon = 0.0000001
def perceptron(x1, x2):
    # 변수 초기화
    w1, w2, b = 1.0, 1.0, -1.5
    # Afine function(f(x)=mx+b)
    sum = x1*w1+x2*w2+b
    # Activation function
    if sum > epsilon:
        return 1
    else:
        return 0

In [20]:
print(perceptron(0,0))
print(perceptron(1,0))
print(perceptron(0,1))
print(perceptron(1,1))

0
0
0
1


In [21]:
# 퍼셉트론(매트릭스)
import numpy as np
epsilon = 0.0000001
def perceptron(x1, x2):
    # 변수 초기화
    X = np.array([x1,x2])
    W = np.array([1.0,1.0])
    b = -1,5
    # Affine function(f(x)=mx+b)
    sum = np.dot(W,X)+b
    # Activation function
    if sum > epsilon:
        return 1
    else:
        return 0

In [23]:
import numpy as np
# 부동 소수점 오차방지
epsilon = 0.0000001
# 활성화 함수(step function)
def step_func(t):
    if t > epsilon:
        return 1
    else:
        return 0
# XOR 연산 학습 데이터
X = np.array([
    [0,0,1],# 맨 끝의 1은 바이어스를 위한 입력신호 1이다.
    [0,1,1],# 맨 끝의 1은 바이어스를 위한 입력신호 1이다.
    [1,0,1],# 맨 끝의 1은 바이어스를 위한 입력신호 1이다.
    [1,1,1] # 맨 끝의 1은 바이어스를 위한 입력신호 1이다.
])

y = np.array([0,1,1,0])
W = np.zeros(len(X[0])) #가중치를 저장하는 행렬

In [28]:
def perceptron_fit(X,Y, epochs=2):
    global W
    # 학습률
    eta = 0.2
    for t in range(epochs):
        print('epoch=',t,'='*10)
        for i in range(len(X)):
            # 예측 값 구하기
            predict = step_func(np.dot(X[i], W))
            # 오차 계산
            error = Y[i] - predict
            # 가중치 업데이트
            W += eta * error * X[i]
            print('현재 처리 입력 = ',X[i], '정답=',Y[i], '예측=', predict, '변경된가중치=',W)
        print('='*20)

In [25]:
X[0]

array([0, 0, 1])

In [26]:
def perceptron_predict(X,Y):
    global W
    for x in X:
        print(x[0],x[1],'->', step_func(np.dot(x,W)))

In [29]:
perceptron_fit(X,y)

epoch= 0 ==========
현재 처리 입력 =  [0 0 1] 정답= 0 예측= 1 변경된가중치= [-0.2  0.   0. ]
현재 처리 입력 =  [0 1 1] 정답= 1 예측= 0 변경된가중치= [-0.2  0.2  0.2]
현재 처리 입력 =  [1 0 1] 정답= 1 예측= 0 변경된가중치= [0.  0.2 0.4]
현재 처리 입력 =  [1 1 1] 정답= 0 예측= 1 변경된가중치= [-0.2  0.   0.2]
epoch= 1 ==========
현재 처리 입력 =  [0 0 1] 정답= 0 예측= 1 변경된가중치= [-0.2  0.   0. ]
현재 처리 입력 =  [0 1 1] 정답= 1 예측= 0 변경된가중치= [-0.2  0.2  0.2]
현재 처리 입력 =  [1 0 1] 정답= 1 예측= 0 변경된가중치= [0.  0.2 0.4]
현재 처리 입력 =  [1 1 1] 정답= 0 예측= 1 변경된가중치= [-0.2  0.   0.2]


In [30]:
W

array([-0.2,  0. ,  0.2])

In [32]:
perceptron_predict(X,y)

0 0 -> 1
0 1 -> 1
1 0 -> 0
1 1 -> 0
